### ISSUE TITLE
Work on bug reports related to stats package

### ISSUE THREAD

**Issue by hturner** [r-devel/r-project-sprint-2023#33]
### Discussed in https://github.com/r-devel/r-project-sprint-2023/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **hturner** August 19, 2023</sup>
This is a list of bugs related to the stats package that would be suitable for sprint participants with a strong statistics background to work on.

| Bug ID                                                    | Level        | Status        | Summary                                     | Language |
|-----------------------------------------------------------|--------------|---------------|---------------------------------------------|----------|
| [18253](https://bugs.r-project.org/show_bug.cgi?id=18253) | Intermediate | patch welcome | family/link specific starting values in glm | R        |
| [14359](https://bugs.r-project.org/show_bug.cgi?id=14359) | Intermediate | patch welcome | enhance t.test() for paired data            | R        |

Only a couple so far - I hope to add to this list.</div>

**Comment by shannonpileggi** [comment]
The suggested changes to t.test are multi-faceted. One element of the Bugzilla discussion relates specifically to the examples section for t.test. In order to isolate the issue, I have created a separate PR. https://github.com/r-devel/r-svn/pull/140/files

Depending on the resulting decision of how to approach the paired t-test, the examples section could be further added to.

**Comment by hanneoberman** [comment]
Update on [18253](https://bugs.r-project.org/show_bug.cgi?id=18253): 
- As Ben Bolker [suggests](https://bugs.r-project.org/show_bug.cgi?id=18253#c3), the name of the link function is not available within the current scope of `binomInitialize()`.
- Changing the default starting values would require a major overhaul to make this available, and therefore not suitable for the R sprint.
- In case there will be a future effort to address this, it might be worth discussing to allow `"binomial"` with an identity link

**Comment by dickoa** [comment]
Here's a PR fixing the issue
https://github.com/r-devel/r-svn/pull/142

**Comment by bastistician** [comment]
> Here's a PR fixing the issue [r-devel/r-svn#142](https://github.com/r-devel/r-svn/pull/142)

I have started a check run for the `stop("cannot use 'paired' in formula method")` proposal in `t.test.formula` and `wilcox.test.formula` over ~5600 CRAN/BIOC packages. I expect that to finish at around 9-10 BST tomorrow morning and will report the results here so that you can discuss the impact in Warwick. (Reviewing/Debugging impacts on packages often takes time; I hope the results will be manageable in this case.)

**Comment by dickoa** [comment]
With @shannonpileggi , @SaranjeetKaur we have submitted a patch to bugzilla 

https://bugs.r-project.org/show_bug.cgi?id=14359

@tslumley please, can you take a look

**Comment by bastistician** [comment]
The check run has finished (took 14.7 hours). I already filtered out some unrelated failures due to broken internet resources.
10 of 5585 checked packages are affected: [diff.txt](https://github.com/r-devel/r-project-sprint-2023/files/12496499/diff.txt). These now have to be investigated and it needs to be discussed if the breakage is justifiable (for these cases and likely elsewhere in analysis scripts etc). I haven't myself studied the PR yet. Maybe you still have some time to discuss the results as part of the Sprint in Warwick.

**Comment by dickoa** [comment]
Thank you @bastistician, we have worked with @tslumley to simplify the patch. You'll find an updated version on Bugzilla. 

https://bugs.r-project.org/show_bug.cgi?id=14359

We'll still have the same number of packages affected because they used `paired` in the formula interface of `t.test` or `wilcox.test`, and it's still throwing an error. We can take  a look at these 10 packages to see if some of them were correct or not.

Thanks

**Comment by aitap** [comment]
- [x] [fix for 14359 committed on 10th of September, PR closed on 11th](https://bugs.r-project.org/show_bug.cgi?id=14359#c22)
 - [ ] [18253: a few comments on 22th of September, but that's it](https://bugs.r-project.org/show_bug.cgi?id=18253#c5)

**Comment by hturner** [comment]
Since Bug 18253 was deemed unsuitable for the sprint I think we can close this issue.
