### ISSUE TITLE
Contribute a welcome patch to base/utils

### ISSUE THREAD

**Issue by hturner** [r-devel/r-project-sprint-2023#34]
### Discussed in https://github.com/r-devel/r-project-sprint-2023/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **hturner** August 17, 2023</sup>
I have been reviewing reports on Bugzilla and have found several where a member of R Core has indicated a patch would be welcome, either by their comments or by adding the HELPWANTED keyword. These bugs are good candidates for contributors to take on at the sprint, though they generally require advanced knowledge of R and/or C. In some cases, the work may extend beyond the sprint, but the sprint can provide an opportunity to get advice from R Core/other experienced contributors.

...
EDIT: table extracted below for updating
...

Additions or corrections to this list are welcome - note I have not checked if the bugs are current in R-devel.

R Core members commenting on original reports: @mmaechler, @ltierney, @bastistician, @s-u.</div>

| Bug ID                                                    | Level        | Topic/Domain    | Summary                                                                    | Language/other | Assigned               |
|-----------------------------------------------------------|--------------|-----------------|----------------------------------------------------------------------------|----------------|------------------------|
| [18255](https://bugs.r-project.org/show_bug.cgi?id=18255) | Intermediate | packages        | requireNamespace doesn't respect min version when namespace already loaded | R              |                        |
| [18380](https://bugs.r-project.org/show_bug.cgi?id=18380) | Intermediate | packages        | passing arguments from check_packages_in_dir() to mclapply()               | R              |                        |
| [17871](https://bugs.r-project.org/show_bug.cgi?id=17871) | Intermediate | utils           | `utils::tar` can produce invalid tarballs w/ long usernames/groupnames     | R              |  Ivan Krylov                      |
| [14354](https://bugs.r-project.org/show_bug.cgi?id=14354) | Advanced     | packages        | mark non-standard evaluation in local scope to be skipped by codetools     | R              |   Lionel Henry, Naras                     |
| [16094](https://bugs.r-project.org/show_bug.cgi?id=16094) | Advanced     | packages        | respect package version restrictions when using `::`                       | R              |                        |
| [16311](https://bugs.r-project.org/show_bug.cgi?id=16311) | Advanced     | base            | set environment variables from env argument                                | C, Windows     |     Ivan Krylov                    |
| [16752](https://bugs.r-project.org/show_bug.cgi?id=16752) | Advanced     | base            | printing complex numbers in R                                              | C              | Jane He, Carol Willing |
| [16856](https://bugs.r-project.org/show_bug.cgi?id=16856) | Advanced     | base            | addition of millisecond adds a second                                      | C              |                        |
| [16034](https://bugs.r-project.org/show_bug.cgi?id=16034) | Advanced     | base            | iterative unserialization for pairlists                                    | C              |                        |
| [17377](https://bugs.r-project.org/show_bug.cgi?id=17377) | Advanced     | utils           | inconsistent result of getSrcLocation for an S4 method that uses `...`     | R              |                        |

**Comment by SiyaoIsHiding** [comment]
Thank you. I believe I can try to work on [16856](https://bugs.r-project.org/show_bug.cgi?id=16856) (addition of millisecond adds a second) too.

**Comment by lionel-** [comment]
I'd be interested to work on [14354](https://bugs.r-project.org/show_bug.cgi?id=14354) or [16034](https://bugs.r-project.org/show_bug.cgi?id=16034).

**Comment by aitap** [comment]
I think I can tackle [17871](https://bugs.r-project.org/show_bug.cgi?id=17871), and I can also try [16311](https://bugs.r-project.org/show_bug.cgi?id=16311).

I was also interested in [14354](https://bugs.r-project.org/show_bug.cgi?id=14354) and [16034](https://bugs.r-project.org/show_bug.cgi?id=16034), but there's already enough work to keep anyone occupied.

**Comment by aitap** [comment]
| Bug ID | Summary | Outcome |
|-|-|-|
| [18255](https://bugs.r-project.org/show_bug.cgi?id=18255) | requireNamespace doesn't respect min version when namespace already loaded |
| ~[18380](https://bugs.r-project.org/show_bug.cgi?id=18380)~ | passing arguments from check_packages_in_dir() to mclapply()               |   [CLOSED FIXED in r85062](https://bugs.r-project.org/show_bug.cgi?id=18380#c2) |
| [17871](https://bugs.r-project.org/show_bug.cgi?id=17871) | `utils::tar` can produce invalid tarballs w/ long usernames/groupnames     | [patch waiting for review](https://bugs.r-project.org/show_bug.cgi?id=17871#c3) |
| [14354](https://bugs.r-project.org/show_bug.cgi?id=14354) | mark non-standard evaluation in local scope to be skipped by codetools     | As of 29th of September, a `declare()` `SPECIALSXP` is available, and so are patches to the `compiler` package (not yet merged) implementing some of the needed declarations. This is by necessity a longer-term project than most. |
| [16094](https://bugs.r-project.org/show_bug.cgi?id=16094) | respect package version restrictions when using `::`                       |
| [16311](https://bugs.r-project.org/show_bug.cgi?id=16311) | set environment variables from env argument                                | [initial patch available, needs discussion; may need a new, better API](https://bugs.r-project.org/show_bug.cgi?id=16311#c5)
| ~[16752](https://bugs.r-project.org/show_bug.cgi?id=16752)~ | printing complex numbers in R                                              | [CLOSED FIXED](https://bugs.r-project.org/show_bug.cgi?id=16752#c11) by radically simplifying complex-printing code. Partially-NA complex numbers are printed as `NA`; otherwise, the numbers are printed separately.
| [16856](https://bugs.r-project.org/show_bug.cgi?id=16856) | addition of millisecond adds a second                                      
| [16034](https://bugs.r-project.org/show_bug.cgi?id=16034) | iterative unserialization for pairlists | As of 25th of September, [a patch is available](https://bugs.r-project.org/show_bug.cgi?id=16034#c12) but not yet merged
| [17377](https://bugs.r-project.org/show_bug.cgi?id=17377) | inconsistent result of getSrcLocation for an S4 method that uses `...`

**Comment by hturner** [comment]
Thanks @aitap for summarising the outcomes for this issue.
