### ISSUE TITLE
Optimize scalar RNG

### ISSUE THREAD

**Issue by gmbecker** [r-devel/r-project-sprint-2023#67]
Endorsed by Luke

Generating scalar random numbers is very slow because the seed is reallocated after each R-level call. It should be possible to avoid this.

**Comment by aitap** [comment]
Do I understand it correctly that the idea is to modify PutRNGState as
follows?

1. Look up .Random.seed
2. If it's already an INTSXP of the right length, not shared, use the
existing data structure and prepare to overwrite its contents
3. Otherwise allocate the R-level variable anew like it was done
previously

Or would it be better to make it an ALTREP that references the contents
of RNG_Table[RNG_kind] without copying?

**Comment by ltierney** [comment]
The options I can think of are

* careful use of reference counts (the best option if it can be made to work, which I think it can)
* using an active binding
* using an altrep

Some things to look for:

* serialization has to work properly
* GetRNGstate has to be able to detect whether the object has been modified from theR level to skip the expensive steps (having a reference count of 2 on the object would ensure that all modifications from R will duplicate)

**Comment by gmbecker** [comment]
Currently a C-side SEXP copy of .Random.Seed is generated and then assigned to the R side within PutRNGState. This isn't really needed provided that the C-side array of ints becomes the source of truth and then can be copied to .Random.Seed only in rare cases when its necessary.

- [ ] - replace "dummy" to INTEGER(<.Random.Seed>) in RNG_Table

Remember, .Random.Seed can Be Unbound, so we need the "old way" to run once, then we update RNG_Table.i_seed


This means that if things are aborted in the middle, the old .Random.Seed value will no longer be preserved.

**Comment by ltierney** [comment]
I've opened this on bugzilla at https://bugs.r-project.org/show_bug.cgi?id=18600
